#!/usr/bin/expect
  
set timeout 20

set password [lindex $argv 0]
set user [lindex $argv 1]
set ip [lindex $argv 2]
set port [lindex $argv 3]
set path [lindex $argv 4]
eval spawn "scp -P $port mysql.sql $user@$ip:$path"
expect "assword:"
send "$password\r";

interact

